# Configuration initiale
GRID_SIZE = 30
INITIAL_SHEEP = 50
INITIAL_WOLVES = 30
INITIAL_GRASS_COVERAGE = 0.3  # 30% de la grille

# Énergie
SHEEP_INITIAL_ENERGY = 20
WOLF_INITIAL_ENERGY = 40
SHEEP_ENERGY_FROM_GRASS = 15
WOLF_ENERGY_FROM_SHEEP = 35
SHEEP_ENERGY_LOSS_PER_TURN = 1
WOLF_ENERGY_LOSS_PER_TURN = 2  # Les loups perdent plus d'énergie

# Reproduction
SHEEP_REPRODUCTION_THRESHOLD = 10
WOLF_REPRODUCTION_THRESHOLD = 40
REPRODUCTION_ENERGY_COST = 10

# Âge
SHEEP_MAX_AGE = 50  # Tours avant mort naturelle
WOLF_MAX_AGE = 70

# Herbe
GRASS_GROWTH_PROBABILITY = 0.08
GRASS_REGROWTH_TIME = 7

# Simulation
MAX_TURNS = 500  # Nombre maximum de tours